src/app/(auth)/login/page.tsx, src/app/(auth)/signup/page.tsx, src/app/(chat)/client/chat/page.tsx, src/app/(chat)/expert/chat/page.tsx, src/app/(chat)/layout.tsx, src/app/commission/page.tsx, src/app/expert/[expert_id]/page.tsx, src/app/expert/become-a-expert/page.tsx, src/app/expert/page.tsx, src/app/expert/register/page.tsx, src/app/myPage/client/page.tsx, src/app/myPage/expert/page.tsx, src/app/myPage/layout.tsx, src/app/order/page.tsx, src/app/store/page.tsx, src/app/store/products/[product_id]/page.tsx
https://www.notion.so/FE-CI-CD-1c14873f28dd8035b28df461ffb46318?pvs=4 위 링크에 상세히 정리되어 있습니다.
=> fix: 도커 빌더 오류 해결

Dockerfile, src/app/(auth)/login/page.tsx, src/app/(auth)/signup/page.tsx, src/app/(chat)/client/chat/page.tsx, src/app/(chat)/expert/chat/page.tsx, src/app/(chat)/layout.tsx, src/app/commission/page.tsx, src/app/expert/[expert_id]/page.tsx, src/app/expert/become-a-expert/page.tsx, src/app/expert/page.tsx, src/app/expert/register/page.tsx, src/app/myPage/client/page.tsx, src/app/myPage/expert/page.tsx, src/app/myPage/layout.tsx, src/app/order/page.tsx, src/app/store/page.tsx, src/app/store/products/[product_id]/page.tsx
https://www.notion.so/FE-CI-CD-1c14873f28dd8035b28df461ffb46318?pvs=4 위 링크에 상세히 정리되어 있습니다.
=> fix: 도커 빌드 오류 해결

.dockerignore, Dockerfile, next.config.ts, package.json, src/components/atoms/mediumTag/MediumTag.stories.tsx, tsconfig.json
빌드 중 발생하던 문재 해결
비정상적으로 높은 용량 해결
=> fix: 도커 빌드, 용량 축소

src/app/globals.css, src/design/Color.mdx, src/design/Typography.mdx
- 스토리 북에 디자인 토큰(color, typography) 문서로 작성하였습니다.
- 파일(Color.mdx, Typography.mdx) 는 일단 design이라는 폴더를 생성하여 하위에 두었습니다. 팀 내부 조율에 따라 파일명 및 위치 수정 가능합니다.
=> [Doc] Storybook 디자인 토큰 문서화

src/app/globals.css, src/components/atoms/standardButton/StandardButton.stories.tsx, src/components/atoms/standardButton/StandardButton.tsx, src/components/atoms/textInput/TextInput.stories.tsx, src/components/atoms/textInput/TextInput.tsx, src/design/Color.mdx, tailwind.config.ts
- TextInput, Button컴포넌트를 구현하였습니다.
- 누락된  accent Color (보라색)을 추가하였습니다.
- 기본 spacing을 조정하였습니다.
=> [FEAT] Atom 레벨의 TextInput, Button컴포넌트 구현

src/app/globals.css, src/components/atoms/cardIcon/CardIcon.tsx, src/components/atoms/comissionInfoItem/ComissionInfoItem.stories.tsx, src/components/atoms/comissionInfoItem/ComissionInfoItem.tsx, src/components/atoms/imageUploadButton/ImageUploadButton.tsx, src/components/atoms/progressBar/ProgressBar.tsx, src/components/atoms/selectedOption/SelectedOption.tsx, src/components/atoms/serviceIntroduction/ServiceIntroduction.stories.tsx, src/components/atoms/serviceIntroduction/ServiceIntroduction.tsx, src/components/atoms/starDefault/StarDefault.stories.tsx, src/components/atoms/starDefault/StarDefault.tsx, src/components/atoms/starTag/StarTag.tsx, src/components/atoms/starWithText/StarWithText.tsx, src/components/molecules/comissionListItem/ComissionListItem.stories.tsx, src/components/molecules/comissionListItem/ComissionListItem.tsx, src/components/molecules/expertListItem/ExpertListItem.stories.tsx, src/components/molecules/expertListItem/ExpertListItem.tsx, src/components/molecules/reviewItem/ReviewItem.stories.tsx, src/components/molecules/reviewItem/ReviewItem.tsx, src/components/molecules/selectedCard/SelectedCard.stories.tsx, src/components/molecules/selectedCard/SelectedCard.tsx, src/utils/dateFormat.ts
- Molecule 레벨의 ExpertListItem, ReviewItem, ComissionListItem 컴포넌트를 구현하였습니다.
- Atom 레벨의 ServiceIntroduction, ComissionInfoItem 컴포넌트를 구현하였습니다.
<table>  
<tr>  
<td><img src="https://github.com/user-attachments/assets/597fdd82-7a5f-40a8-a8ce-5fcf1c8dfbb7" /></td>  
<td><img src="https://github.com/user-attachments/assets/b8f8ae47-e673-479f-aab5-f0203cac72ad"  /></td>  
</tr>  
<tr>  
<td><img src="https://github.com/user-attachments/assets/1972f5ef-31af-4f44-908e-83c7cbdc6e15"  /></td>
<td><img src="https://github.com/user-attachments/assets/7ce9560a-438e-4511-adc7-1c405f41133a"  /></td>
</tr>  
<tr>  
<td><img src="https://github.com/user-attachments/assets/6cf90cde-07de-4c48-936d-9181c894d865"  /></td>
</tr>  
</table>
=> [FEAT] Expert, Comission Page Molecules 제작

src/components/molecules/expertListItem/ExpertListItem.tsx, src/components/molecules/productListItem/ProductListItem.stories.tsx, src/components/molecules/productListItem/ProductListItem.tsx, src/components/molecules/reviewItem/ReviewItem.tsx
- 기본 이미지를 DefaultImage.png로 변경
=> [REFACTOR] 기본 이미지를 DefaultImage.png로 변경

src/components/atoms/icons/dopdangLogo/DopdangLogo.stories.tsx, src/components/atoms/icons/dopdangLogo/DopdangLogo.tsx, src/components/molecules/navigationLink/NavigationLinks.stories.tsx, src/components/molecules/navigationLink/NavigationLinks.tsx
=> feat: 누락된 모듈 추가

src/components/templates/auth/loginTemplate/LoginPageTemplate.tsx, src/components/templates/auth/signupTemplate/signupPageTemplate.tsx, src/types/api.ts, src/utils/API.ts, src/utils/APIBuilder.ts, src/utils/apiInstance.ts
- **API 클래스 추가**  
- 기본 API 호출 기능을 제공하는 `API` 클래스 구현  
- URL 파라미터, 헤더, 요청 본문 및 타임아웃 처리 기능 포함  
- 오류 처리 및 응답 데이터 반환 로직 추가  
- **APIBuilder 클래스 구현**  
- API 요청을 위한 빌더 패턴 도입  
- `GET`, `POST`, `PUT`, `DELETE`, `PATCH` 등 다양한 HTTP 메서드 지원  
- API 호출 시 헤더, 데이터, 타임아웃 및 기타 설정 가능  
- 기존 `apiInstance`와의 호환성을 위한 래퍼 함수 추가  
- **API 타입 정의 및 `apiInstance` 리팩토링**  
- HTTP 메서드, 헤더, 파라미터 및 응답 타입 정의를 위한 `api.ts` 파일 추가  
- 기존 `apiInstance`를 `APIBuilder`를 사용하여 리팩토링 → 코드 간결화 및 타입 안전성 향상  
- API 호출 시 타입 안전한 방식으로 헤더 설정 적용  
- **로그인 및 회원가입 API 리팩토링**  
- 로그인 및 회원가입 요청에서 `apiInstance`를 `APIBuilder`로 변경 → 가독성 및 유지보수성 개선  
- 회원가입 템플릿의 전화번호 인증 API 호출도 `APIBuilder`를 사용하도록 수정  
**API 요청 예시**
```tsx
const response = await APIBuilder.post('/auth/login', { username: 'user', password: 'pass' }) …
```
=> [FEAT] APIBuilder 도입 및 API 구조 리팩토링

src/components/molecules/socialLoginButtonConainter/SocialLoginButtonConainter.tsx
- **소셜 로그인 버튼 컴포넌트 리팩토링**  
- 컴포넌트 구조 개선 및 재사용성 향상  
- 버튼 스타일 및 아이콘 정렬 개선  
- **에러 처리 로직 추가**  
- 소셜 로그인 과정에서 발생할 수 있는 예외 케이스 핸들링  
- 사용자에게 명확한 피드백 제공을 위한 에러 메시지 출력 추가
=> [FEAT] 소셜 로그인 버튼 기능 구현

package-lock.json, package.json, src/components/atoms/buttons/imageUploadButton/ImageUploadButton.tsx, src/utils/compressImage.ts, src/utils/getFileSizeAndDimensions.ts
=> feat: 이미지 압축 코드 도입

src/utils/APIBuilder.ts
=> feat: 베이스 url 변경

src/apis/review/getExpertReviews.ts, src/app/myPage/myProject/page.tsx, src/app/myPage/receivedReview/page.tsx, src/app/myPage/serviceStatus/page.tsx, src/components/molecules/emptyState/EmptyState.tsx, src/components/molecules/navigation/profileDropdown/ProfileDropdown.tsx
- 전문가 리뷰 조회 기능에 페이지네이션 로직 추가 및 API 개선  
- 프로젝트 상태 관리 로직 리팩터링으로 가독성 및 유지보수성 향상  
- 더보기 버튼을 `StandardButton` 컴포넌트로 교체하여 UI 일관성 확보  
- 프로필 드롭다운 컴포넌트 스타일 개선
=> [FEAT] 마이페이지 전문가 리뷰 조회 기능 구현

src/apis/expert/getExpert.ts, src/apis/main/getPopularExpert.ts, src/apis/project/getProjectsAll.ts, src/app/commission/page.tsx, src/app/expert/[id]/page.tsx, src/components/molecules/commissionListItem/ComissionListItem.tsx, src/components/organisms/expertDetail/expertIntroduction/ExpertIntroduction.tsx, src/components/templates/commissionTemplate/CommissionDetailTemplate.tsx, src/components/templates/commissionTemplate/CommissionTemplate.tsx
=> 커미션 페이지 필터링 기능 추가

src/middleware.ts
=> fix: 미들웨어 업데이트

src/middleware.ts
=> fix: request.cookies

src/middleware.ts
=> fix: request.cookies.get(accessToken)

src/middleware.ts
=> fix: request.cookies.get(accessToken).value

src/middleware.ts
=> fix: requestToken 가드 적용

src/middleware.ts
=> fix: requestToken 옵셔널 적용

next.config.ts, src/components/molecules/modal/ModalContainer.tsx, src/components/molecules/projectItemCard/ProjectItemCard.tsx, src/components/organisms/HomePage/popularExpertSection/PopularExpertSection.tsx, src/components/organisms/desktopNavigation/DesktopNavigation.tsx, src/components/organisms/orderCard/OrderCard.tsx, src/components/templates/homePageTemplete/HomePage.tsx
- **주문 카드 개선**  
- 주문 카드에 *구매 취소 모달* 추가  
- 버튼 스타일 및 레이아웃 개선  
- **인기 전문가 섹션 개선**  
- 데이터 *로딩 상태* 및 *에러 처리* 로직 추가로 사용자 경험 향상  
- **ProjectItemCard 개선**  
- 내부 버튼을 `article` 태그로 리팩토링하여 시맨틱 구조 강화  
- **그 외 수정 사항**  
- 이미지 도메인 환경변수 추가  
- 사용자 데이터 병합 로직 수정으로 예외 처리 강화
=> [FEAT] 주문 취소 기능 추가 및 인기 전문가 섹션 개선, 로그인 새로고침 시 로직 수정

src/apis/user/getCurrentUser.ts
=> fix: getCurrentUser api 파스 변경  /users/me -> /users/profile

src/components/templates/auth/loginTemplate/LoginPageTemplate.tsx
=> fix: 로그인 인식 못하는 문제 해결

src/app/commission/page.tsx
=> fix: commission 조회 0번부터 시작

src/components/organisms/desktopFooter/DesktopFooter.tsx, src/components/organisms/desktopNavigation/DesktopNavigation.tsx, src/components/templates/homePageTemplete/HomePage.tsx
- Footer 컴포넌트를 제작하여 홈페이지에 추가하였습니다.
=> [FEAT] 홈페이지에 Footer 추가

src/app/commission/page.tsx, src/components/templates/commissionTemplate/CommissionTemplate.tsx
=> fix: commission 필터 오류 해결

src/apis/store/getProductList.ts, src/components/atoms/filePreview/FilePreview.tsx, src/components/molecules/chat/ChattingButtonGroup.tsx, src/components/molecules/chat/ChattingExpertInfo.tsx, src/components/molecules/messageTemplate/MessageTemplate.tsx, src/components/organisms/chatting/chattingInfo/client/ClientChattingInfo.tsx, src/components/organisms/chatting/chattingInfo/expert/ExpertChattingInfo.tsx, src/components/organisms/chatting/chattingLIst/ChattingList.tsx, src/components/organisms/chatting/chattingRoom/ChattingRoom.tsx, src/components/organisms/projectSummary/ProjectSummary.tsx, src/components/organisms/store/StoreProductImageTitle.tsx, src/components/templates/chatTemplate/ChattingTemplate.tsx, src/components/templates/chatTemplate/ExpertChattingTemplate.tsx, src/components/templates/store/storeMain/StoreMainTemplate.tsx
- 채팅방 목록검색 기능구현
- 채팅방 나가기 기능 추가
- 채팅방 이미지 파일 전송 기능 구현
- 스토어 재고관련 버그 수정
* 현재 백엔드 Db 관련 문제로 채팅방 목록에 가장 최근 메세지가 Null 로 들어오는 오류 있습니다.
* 백엔드 채팅로직 상에서 알 수 없는 오류로 간헐적으로 채팅 내역이 저장되지 않는 오류가 발생합니다.
=> [FEAT] 채팅방 추가기능(파일 전송, 채팅방 나가기, 채팅읽음 실시간), 스토어 버그 수정

src/components/molecules/chat/ChattingButtonGroup.tsx, src/components/molecules/inputTemplate/InputTemplate.tsx, src/components/organisms/chatting/chattingInfo/expert/ExpertChattingInfo.tsx, src/components/organisms/chatting/chattingRoom/ChattingRoom.tsx
- 채팅방 관련 api Base url을 배포 서버로 변경
=> fix : 로컬 서버대신 개발서버로 변경

src/components/molecules/chat/ChattingButtonGroup.tsx, src/components/organisms/chatting/chattingInfo/expert/ExpertChattingInfo.tsx, src/components/organisms/chatting/chattingRoom/ChattingRoom.tsx
=> fix : 배포서버로 base url 변경

src/apis/review/createReview.ts, src/apis/store/updateProduct.ts, src/components/molecules/orderListItem/OrderListItem.tsx
- 상품 정보 수정 API 메서드 수정
- 리뷰 생성 API 수정
=> [FEAT] 상품 정보 수정, 리뷰 생성 API 수정

src/components/organisms/chatting/chattingRoom/ChattingRoom.tsx
=> chore : 콘솔 제거

src/apis/expert/getExpertlist.ts, src/apis/store/getProductList.ts, src/app/expert/[id]/page.tsx, src/app/expert/page.tsx, src/app/store/products/[product_id]/page.tsx, src/components/molecules/order/resultButtons/ResultButtons.tsx, src/components/organisms/expertDetail/expertIntroduction/ExpertIntroduction.tsx, src/components/organisms/store/StoreDetailInfo.tsx, src/components/templates/store/storeProductDetail/StoreProductDetailTemplate.tsx, src/middleware.ts, src/utils/decodeToken.ts
-버그 수정( 전문가 의뢰인 역할 수정, 전문가 이름 검색)
=> [FIX] 버그 수정( 전문가 의뢰인 역할 수정, 전문가 이름 검색)

src/apis/main/getPopularExpert.ts, src/components/molecules/popularExpertItem/PopularExpertItem.tsx
=> chore: review -> reviewCounts 네이밍

src/apis/project/getProject.ts, src/apis/review/getExpertReviews.ts, src/app/expert/[id]/page.tsx, src/app/expert/make-offer/page.tsx, src/components/molecules/reviewItem/ReviewItem.tsx, src/components/organisms/expertDetail/expertIntroduction/ExpertIntroduction.tsx, src/components/organisms/expertDetail/expertProfile/ExpertProfile.tsx
=> [FIX] 디버깅을 위한 콘솔로그 추가, 전문가 페이지 리뷰 띄우도록 수정

src/apis/project/getProject.ts
=> fix: 프로젝트 단건조회 엔드포인트 변경

src/apis/project/getProjectInClient.ts
=> feat: 프로젝트 엔드포인트 변경

src/components/molecules/chat/ChattingButtonGroup.tsx, src/components/organisms/chatting/chattingInfo/client/ClientChattingInfo.tsx, src/components/templates/makeOfferTemplate/MakeOfferTemplate.tsx
=> REFACTOR : alert 문 제거, 채팅방 나가기 버튼 보여지는 조건 제거

src/components/organisms/chatting/chattingInfo/client/ClientChattingInfo.tsx, src/components/templates/chatTemplate/ChattingTemplate.tsx
=> refactor : offerData, expertData 가 있어야 채팅방 버튼 띄우도록 변경

src/components/atoms/inputs/numberInput/NumberInput.tsx, src/components/molecules/modal/ContractModal.tsx, src/components/organisms/offerForm/OfferForm.tsx
=> FIX : number input의 기본값 null로 변경

src/app/expert/page.tsx, src/components/molecules/expert/expertListItem/ExpertListItem.tsx, src/components/molecules/order/resultBanner/ResultBanner.tsx, src/components/templates/makeOfferTemplate/MakeOfferTemplate.tsx, src/constants/category.ts
=> FIX : 전문가 카테고리 이름 수정

src/app/expert/page.tsx, src/components/organisms/HomePage/storeCategorySection/StoreCategorySection.tsx, src/components/organisms/store/StoreSearchResgister.tsx, src/components/templates/store/storeMain/StoreMainTemplate.tsx
=> fix : 메인페이지에서 스토어 컴포넌트 진입하는 로직 수정

src/app/(payment)/payments/page.tsx, src/components/atoms/buttons/PaymentButton.tsx, src/components/templates/orderTemplate/OrderTemplate.tsx
=> FIx: 수량 보이도록 변경, 최종 금액으로 결제창 오픈
